"""empty message

Revision ID: 032d8f49f632
Revises: eeb091fb85d1
Create Date: 2022-08-08 16:19:43.532139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032d8f49f632'
down_revision = 'eeb091fb85d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('City_and_State_Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('City_and_State_Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('city_state_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Artist', 'City_and_State_Artist', ['city_state_id'], ['id'])
    op.drop_column('Artist', 'state')
    op.drop_column('Artist', 'city')
    op.add_column('Venue', sa.Column('city_state_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'City_and_State_Venue', ['city_state_id'], ['id'])
    op.drop_column('Venue', 'state')
    op.drop_column('Venue', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'city_state_id')
    op.add_column('Artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'city_state_id')
    op.drop_table('City_and_State_Venue')
    op.drop_table('City_and_State_Artist')
    # ### end Alembic commands ###
