"""empty message

Revision ID: 09aa60bb5015
Revises: 69c19262ee71
Create Date: 2022-08-11 20:27:14.343983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09aa60bb5015'
down_revision = '69c19262ee71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist_Available_Days', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Artist_Available_Days', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist_Available_Days', type_='foreignkey')
    op.drop_column('Artist_Available_Days', 'artist_id')
    # ### end Alembic commands ###
