"""empty message

Revision ID: 1784fe8a48f7
Revises: 9e1693df2c9d
Create Date: 2022-08-15 17:07:41.461525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1784fe8a48f7'
down_revision = '9e1693df2c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_city_state_id_fkey', 'Artist', type_='foreignkey')
    op.create_foreign_key(None, 'Artist', 'City_and_State_Artist', ['city_state_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Artist_Available_Days_artist_id_fkey', 'Artist_Available_Days', type_='foreignkey')
    op.create_foreign_key(None, 'Artist_Available_Days', 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Show_artist_id_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_venue_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Venue_city_state_id_fkey', 'Venue', type_='foreignkey')
    op.create_foreign_key(None, 'Venue', 'City_and_State_Venue', ['city_state_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.create_foreign_key('Venue_city_state_id_fkey', 'Venue', 'City_and_State_Venue', ['city_state_id'], ['id'])
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venue_id_fkey', 'Show', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key('Show_artist_id_fkey', 'Show', 'Artist', ['artist_id'], ['id'])
    op.drop_constraint(None, 'Artist_Available_Days', type_='foreignkey')
    op.create_foreign_key('Artist_Available_Days_artist_id_fkey', 'Artist_Available_Days', 'Artist', ['artist_id'], ['id'])
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.create_foreign_key('Artist_city_state_id_fkey', 'Artist', 'City_and_State_Artist', ['city_state_id'], ['id'])
    # ### end Alembic commands ###
