"""empty message

Revision ID: 5606f7deb145
Revises: e9b1c41334dd
Create Date: 2022-08-11 14:40:17.516921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5606f7deb145'
down_revision = 'e9b1c41334dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('Artist', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('Venue', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'updated_at')
    op.drop_column('Venue', 'created_at')
    op.drop_column('Artist', 'updated_at')
    op.drop_column('Artist', 'created_at')
    # ### end Alembic commands ###
