"""empty message

Revision ID: 9e1693df2c9d
Revises: d8493ef6218a
Create Date: 2022-08-15 17:00:02.165171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e1693df2c9d'
down_revision = 'd8493ef6218a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('Show', 'update_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Show', 'updated_at')
    # ### end Alembic commands ###
