"""empty message

Revision ID: b51be4c076ae
Revises: 1672341a65d1
Create Date: 2022-08-09 21:48:29.110635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51be4c076ae'
down_revision = '1672341a65d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.String(length=120), nullable=False))
    op.add_column('Show', sa.Column('created_at', sa.String(length=120), nullable=False))
    op.add_column('Show', sa.Column('updated_at', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'updated_at')
    op.drop_column('Show', 'created_at')
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
