"""empty message

Revision ID: d8493ef6218a
Revises: a8e26077a2ba
Create Date: 2022-08-15 16:59:50.625516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8493ef6218a'
down_revision = 'a8e26077a2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_column('Show', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Show', 'update_at')
    # ### end Alembic commands ###
