"""empty message

Revision ID: da25805561b4
Revises: c17d6881d7a4
Create Date: 2022-08-15 13:40:40.855993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da25805561b4'
down_revision = 'c17d6881d7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('Genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'Genres')
    # ### end Alembic commands ###
