"""empty message

Revision ID: e9b1c41334dd
Revises: bb35896fe13c
Create Date: 2022-08-10 11:44:03.055704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b1c41334dd'
down_revision = 'bb35896fe13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('Show', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('Show', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'updated_at')
    op.drop_column('Show', 'created_at')
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
